# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/
# dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  # Enable version updates for pub (Flutter/Dart)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "flutter"
    groups:
      minor-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"
