name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            build-targets: ios,macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        if: contains(matrix.build-targets, 'ios')
        run: |
          flutter build ios --release --no-codesign

      - name: Build macOS
        if: contains(matrix.build-targets, 'macos')
        run: |
          flutter build macos --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-${{ matrix.os }}
          path: |
            build/ios/iphoneos
            build/macos/Build/Products/Release
